name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]
jobs:
  parsing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Nix
        uses: cachix/install-nix-action@v8
      - name: Prefetch shell.nix
        run: 'nix-shell --run true'
      - name: Parsing
        run: './ci/check-nix-files.sh'
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Nix
        uses: cachix/install-nix-action@v8
      - name: Prefetch shell.nix
        run: 'nix-shell --run true'
      - name: Black
        run: './ci/check-formatting.sh'
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Nix
        uses: cachix/install-nix-action@v8
      - name: Prefetch shell.nix
        run: 'nix-shell --run true'
      - name: Mypy
        run: './ci/check-mypy.sh'
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Nix
        uses: cachix/install-nix-action@v8
      - name: Build
        run: 'nix-build -I nixpkgs=channel:nixos-20.03 --quiet release.nix -A nixops-grafana.x86_64-linux'
